docs/API/Users_Guide/Getting_Started.md
docs/API/Users_Guide/Python_Examples.md
docs/API/Users_Guide/scripts/Authentication_Tokens.py
docs/API/Users_Guide/scripts/Basic_Query.py
docs/API/Users_Guide/scripts/Basic_Troubleshooting.py
docs/API/Users_Guide/scripts/Complex_Query.py
docs/API/Users_Guide/scripts/Filter_Query.py
docs/API/Users_Guide/scripts/Sample_Request.py
docs/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md

Modified the Python scripts in "Getting Started" and "Python Examples" pages so the script will (wherever applicable) save the results to a file in addition to displaying on screen.

masifor210203

---

docs/Data_Portal/Publication/HTML_Pages/TARGET_ALL-P1.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_ALL-P2.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_ALL-P3.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_AML.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_CCSK.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_NBL.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_OS.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_RT.html
docs/Data_Portal/Publication/HTML_Pages/TARGET_WT.html

Removed clinical files from 9 files in HTML_Pages

Removed clinical files from HTML_Pages

---

theme/404.html
theme/base.html

The NCI is changing how their analytics scripts are loaded.  This commit removes the old script and add the new one.

PEAR-805 switch to new analytics

---

.gitignore
theme/apps/dictionary/scripts/dictionary-views.js
theme/apps/dictionary/scripts/dictionary.js

There are two commits in this PR.  The commits should not be squashed when merging.
The first commit is only code formatting changing. 
The actual changes for this ticket are in the second commit.
Example of what arrays look like:

PEAR-1138 Update dictionary viewer to display values for enum arrays

---

docs/Data_Dictionary/Release_Notes/Data_Dictionary_Release_Notes.md

Adding data dictionary release notes for Galileo release

data dict release note updates galileo

---

docs/Data_Portal/Users_Guide/BAMslicing.md

Fix urls to image folder to remove prefix

update image links

---

Data_Portal_UG.yml
docs/Data_Portal/Users_Guide/Video_Tutorials.md
docs/Data_Portal/Users_Guide/cohort_builder.md
docs/Data_Portal_V1/Release_Notes/Data_Portal_V1_Release_Notes.md

fix broken links

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
docs/Data_Portal/Users_Guide/quick_start.md

- added blank lines so bullets render correctly
- adding prelim release notes > known issues, including DOC-401/DOC-346

Misc updates, release notes

---

docs/Data_Portal/Users_Guide/Projects.md
docs/Data_Portal/Users_Guide/Repository.md
docs/Data_Portal/Users_Guide/analysis_center.md
docs/Data_Portal/Users_Guide/cohort_builder.md
docs/Data_Portal/Users_Guide/cohort_comparison.md
docs/Data_Portal/Users_Guide/getting_started.md

Only the changed pages have been reviewed.  Will create a PR later for the others.
- Changed some wording
- Fixed places where docs didn't render correctly
- Tried to fix quick_start -- getting_started mixup (let me know if I miss any)
Planned PR: Change order of menu list.

Fixes misc

---

docs/Data_Portal/Users_Guide/quick_start.md

Converting to HTML

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

Still in progress since there may be new bugs found between now and release.

2.0 release notes

---

docs/Data_Portal/Users_Guide/Projects.md
docs/Data_Portal/Users_Guide/clinical_data_analysis.md
docs/Data_Portal/Users_Guide/cohort_comparison.md
docs/Data_Portal/Users_Guide/getting_started.md

* DOC-269: adds info about p-value to Cohort Comparison
* DOC-267: adds link to DTT in Projects 
* DOC-268: adds info on resetting bins in cDAVE; removed info about bins being saved per analysis (a V1-only thing)
* adds info about dynamic cohorts and data releases, how to get a snapshot of cohort

Misc updates

---

docs/Data_Portal/Users_Guide/getting_started.md

fixes grammar

---

docs/Data_Portal/Users_Guide/Video_Tutorials.md

Revert "no youtube playlist yet"

---

docs/Data_Portal/Users_Guide/gene_expression_clustering.md

Fixing images on gene expression clustering page

Fixing images on gene expression clustering page

---

docs/Data_Portal/Users_Guide/gene_expression_clustering.md

Sorry - fixed a previously broken image but left the broken link below. Deleted it in this PR

Deleting duplicate image that was fixed above

---

docs/Data_Portal/Users_Guide/cohortMAF.md

Small changes to cohortMAF.md to match other GDC documentation

Updating cohortMAF.md

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- Release notes based on current portal RC of Kepler for UC.
Figured it's good to have a draft in so we can easily incorporate SJ's notes. 
I left SJ's 508 known issues as-is from 2.0 since I don't think there are many changes in that are for 2.1, but I removed their other known issues since they've been making a lot of changes there.

first pass at kepler release notes draft

---

docs/Data_Portal/Users_Guide/Repository.md
docs/Data_Portal/Users_Guide/cohort_builder.md

- adds some clarification about filters in Cohort Builder vs Repository

DOC-416 clarify filters in cohort builder vs repository

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- adds known issue about aggregated MAF and sequence reads/bam slicing
- some styling adjustments

last minute kepler known issues

---

mkdocs.yml
theme/404.html

Resolved conflicts with master branch

Merged master into develop 

---

docs/Data_Dictionary/Release_Notes/Data_Dictionary_Release_Notes.md
docs/Data_Submission_Portal/Users_Guide/Best_Practices.md

Leeuwenhoek release notes draft

Leeuwenhoek release notes

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- first pass at McClintock release notes based on current cut of release branch.
- also changed "pp" to "proteinpaint" for release notes. other instances of "pp" will be fixed in a separate PR for users' guide.

McClintock release notes first draft

---

docs/API/Users_Guide/Data_Analysis.md

Draft for Gene Expression APIs

DOC-428 Draft for Gene Expression APIs

---

docs/Data_Portal/Users_Guide/Repository.md

- added info about the 4 new biospecimen filters in the Repository

DOC-424 updates repository docs with new biospecimen filters

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- adds SJ's release notes
- adds age of index known issues
- expand known issues for 0 cases and strict AND

Final release notes for McClintock

---

docs/API/Users_Guide/Submission.md

Adding PATCH method

---

docs/Encyclopedia/pages/GATK4_MuTect2_Tumor-Only.md
docs/Encyclopedia/pages/GATK4_MuTect2_Tumor-Only_Annotation.md
docs/Encyclopedia/pages/MuSE.md
docs/Encyclopedia/pages/MuSE_Annotation.md
docs/Encyclopedia/pages/MuTect2.md
docs/Encyclopedia/pages/MuTect2_Annotation.md

Drafts for GATK4 MuTect2 Tumor-Only Annotation, GATK4 MuTect2 Tumor-Only, MuSE Annotation, MuSE, MuTect2 Annotation, and MuTect2 workflows.
MuSE and MuTect2 have been written before but I changed them slightly so it makes sense to check them as well.

DOC-425 part 5: GATK4 MuTect2 Tumor-Only Annotation, GATK4 MuTect2 Tumor-Only, MuSE Annotation, MuSE, MuTect2 Annotation, and MuTect2

---

docs/API/Users_Guide/Data_Analysis.md

formatting changes for Gene Expression Values Endpoint and Gene Expression Gene Selection Endpoint

DOC-428:  formatting changes

---

docs/Data_Portal/Users_Guide/Developers_Guide.md

Adds style guide to developer's guide.

Add design kit to developer's guide

---

mkdocs.yml

Adding troubleshooting guide to mkdocs.yml

Adding troubleshooting guide to mkdocs.yml

---

docs/Data_Submission_Portal/Users_Guide/Troubleshooting.md

Attempting to separate examples

Separating examples

---

docs/Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
docs/Encyclopedia/pages/FoundationOne_Annotation.md
docs/Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md

Drafts for FM Simple Somatic Mutation, FoundationOne Annotation and FoundationOne Variant Aggregation and Masking workflows. I'm less sure about these workflows as they don't have that much info.

DOC-425 part 4: FM Simple Somatic Mutation, FoundationOne Annotation and FoundationOne Variant Aggregation and Masking

---

docs/Encyclopedia/pages/VCF_LiftOver.md
docs/Encyclopedia/pages/VarScan2.md
docs/Encyclopedia/pages/VarScan2_Annotation.md

Drafts for VarScan2, VarScan2 Annotation, VCF LiftOver workflows

DOC-425 part 7: VarScan2, VarScan2 Annotation, VCF LiftOver

---

mkdocs.yml
overrides/partials/search.html

Overrides search partial and adds the necessary aria-label.

PEAR-2112 - Resolve 508 issue with doc site search dialog

---

.secrets.baseline
docs/Data_Dictionary/Release_Notes/Data_Dictionary_Release_Notes.md

okazaki release note updates + updates to .secrets.baseline

okazaki release draft notes

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
docs/Data_Submission_Portal/Users_Guide/Pre_Release_QC.md

Fixing broken links per [DOC-448](https://gdc-ctds.atlassian.net/browse/DOC-448)

Fixing broken links

---

docs/Encyclopedia/pages/CaVEMan.md
docs/Encyclopedia/pages/CellRanger_10x_Chromium.md
docs/Encyclopedia/pages/CellRanger_10x_Filtered_Counts.md
docs/Encyclopedia/pages/CellRanger_10x_Raw_Counts.md
docs/Encyclopedia/pages/DNAcopy.md

Drafts for CaVEMan, CellRanger_10x_Chromium, CellRanger_10x_Filtered_Counts, CellRanger_10x_Raw_Counts, DNAcopy workflows

DOC-425 part 3: Drafts for CaVEMan, CellRanger_10x_Chromium, CellRanger_10x_Filtered_Counts, CellRanger_10x_Raw_Counts, DNAcopy workflows

---

docs/Encyclopedia/pages/BWA-aln.md
docs/Encyclopedia/pages/BWA_with_BQSR.md
docs/Encyclopedia/pages/BWA_with_Mark_Duplicates_and_BQSR.md

Drafts for BWA with BQSR, BWA with Mark Duplicates and BQSR, and BWA-aln workflows

DOC-425 part 8: BWA with BQSR, BWA with Mark Duplicates and BQSR, and BWA-aln

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- first draft for Pauling release notes, mostly to make it easier for different parties to work on different parts later

first draft for pauling release notes

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- added feature and 508 changes
- updated known issues
- bug fixes 
__
SJ's changes will be in a separate PR.

Pauling release notes draft 2

---

.gitignore
docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- added SJ's release notes
- added a UC known issue
- some reorganization

Pauling release notes final

---

docs/API/Release_Notes/API_Release_Notes.md

API release notes about new submission permissions.

API release notes for Q

---

docs/Data/Release_Notes/Data_Release_Notes.md

DR42 Release Notes

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- updates portal release notes with info about cohort comparison's negative cases (DOC-472)

DOC-472 adds cohort comparison negative cases info

---

docs/Data/Bioinformatics_Pipelines/DNA_Seq_WGS.md

Attempting to fix encoding issues (no exact position provided in terminal output)

Fixing encoding issues

---

docs/Data/Release_Notes/Data_Release_Notes.md

DR42 manifests

---

docs/Data/Release_Notes/Data_Release_Notes.md

Updating link

---

docs/API/Users_Guide/Data_Analysis.md

Add cnv_change_5_category to API documentation

Add cnv_change_5_category to API documentation

---

docs/API/Users_Guide/Appendix_A_Available_Fields_old.md

Updating API Appendix A per https://gdc-ctds.atlassian.net/browse/DOC-200

Updating API Appendix A

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

This is a draft of the release notes for the Roentgen release so SJ can more easily slot their release notes in. There will likely be edits later for the final version (e.g. better organization, wording tweaks).

Roentgen release notes draft

---

docs/API/Users_Guide/Data_Analysis.md

Adding documentation of scRNA-Seq Gene Expression API to Data Analysis doc

scRNA-Seq Gene Expression Endpoints - Data Analysis API doc

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
docs/Data_Submission_Portal/Users_Guide/Data_Submission_Walkthrough.md

- DOC-466 and DOC-465: adds known issues
- DOC-122: updates link

updates known issues and link

---

mkdocs.yml

Workflows from https://github.com/NCI-GDC/gdc-docs/pull/368 and https://github.com/NCI-GDC/gdc-docs/pull/357:
BWA with BQSR, BWA with Mark Duplicates and BQSR, BWA-aln, CaVEMan, CellRanger_10x_Chromium, CellRanger_10x_Filtered_Counts, CellRanger_10x_Raw_Counts, and DNAcopy workflows

DOC-425: Added 8 Workflow Types to mkdocs.yml

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

- updates release dates
- minor punctuation and wording changes
- some ordering changes of items

updates release date, minor fixes

---

docs/Data_Dictionary/viewer/dictionary-views.js

PEAR-2385 - Dictionary Viewer displays Biospecimen nodes in reversed alphabetical order

---

docs/Data/Bioinformatics_Pipelines/DNA_Seq_WGS.md
docs/Data/Release_Notes/Data_Release_Notes.md

I know we'll have to fix the date, but this should be the release notes and bioinfo updates.

DR43 release notes

---

.secrets.baseline
docs/API/Users_Guide/Additional_Examples.md
docs/API/Users_Guide/Data_Analysis.md
docs/API/Users_Guide/Python_Examples.md
docs/API/Users_Guide/scripts/Download_Files_Filter.py

Updating outdated info: scripts, shells, filters, etc

DOC-489: Updating outdated info: scripts, shells, filters, etc

---

docs/API/Users_Guide/BAM_Slicing.md
docs/API/Users_Guide/Data_Analysis.md
docs/API/Users_Guide/Downloading_Files.md
docs/API/Users_Guide/Python_Examples.md
docs/API/Users_Guide/Search_and_Retrieval.md
docs/API/Users_Guide/scripts/BAM_Slice.py
docs/API/Users_Guide/scripts/BAM_Slice_Multiple.py
docs/API/Users_Guide/scripts/Download_Files.py
docs/API/Users_Guide/scripts/Download_Files_Post.py
docs/API/Users_Guide/scripts/Download_Files_Token.py
docs/Data_Portal/Users_Guide/Developers_Guide.md

DOC-487 changes to update outdated UUIDs
https://gdc-ctds.atlassian.net/browse/DOC-487

DOC-487 changes to update outdated UUIDs

---

docs/Data/File_Formats/MAF_Format.md

Update MAF_Format doc per https://gdc-ctds.atlassian.net/browse/DOC-420

Update MAF_Format doc

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

This PR adds release notes for ProteinPaint-based analysis tools.

Add release notes for the ProteinPaint-based tool updates and fixes

---

Encyclo_Dev/Under_Development/Biospecimen_Supplement.md
docs/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline.md
docs/Data_Portal/Users_Guide/mutation_frequency.md
docs/Encyclopedia/pages/Clinical_Supplement.md

Fixes broken links - DOC-297.
- note that I didn't fix links in v1 release notes, v1 user guide, or webinar description

Fixes some broken links

---

docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md

Added known issues for ProteinPaint-based tools in Sanger release notes

add known issues for ProteinPaint-based tools in Sanger release notes

---

docs/Data_Dictionary/viewer/dictionary.js

Support deprecated enums in array properties

PEAR-2395 - Dictionary viewer, hide deprecated enums

---

docs/Data_Dictionary/viewer/dictionary.js

Fix style not accepting object in recent d3 version

PEAR-2481 - Add breadcrumbs back to dictionary viewer
